[package]
name = "watchrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "3"
crossterm = "0.29"
serde = { version = "1.0.219", features = ["derive"] }
sysinfo = "0.36"
toml = "0.9.2"
